# (Feature Scaling)

Before exploring about all other aspects, it is essential to know a bit about it. Well, Feature scaling, in the context of machine learning, refers to the process of transforming the numerical features of a dataset into a standardized range. involves bringing all the features to a similar scale, so that no single feature dominates the learning algorithm. By scaling the features, we can ensure that they contribute equally to the model’s performance.

## Role of Feature Scaling in Machine Learning

Feature scaling plays a crucial role in machine learning for a variety of reasons:

<ol>
  <li>Many machine learning algorithms use distance-based calculations to make predictions. If the features are not scaled, those with larger values can have a disproportionate impact on the results.</li>
  <li>Feature scaling can help improve the convergence speed and performance of some optimization algorithms.</li>
  <li>This helps in handling skewed data and outliers, which can influence the model’s behavior.</li>
</ol>

## Importance of Feature Scaling in Machine Learning

### 1) Enhancing Model Performance:

Feature scaling can significantly enhance the performance of machine learning models. Scaling the features makes it easier for algorithms to find the optimal solution, as the different scales of the features do not influence them. It can lead to faster convergence and more accurate predictions, especially when using algorithms like k-nearest neighbors, support vector machines, and neural networks.

### 2) Addressing Skewed Data and Outliers:

Skewed data and outliers can negatively impact the performance of machine learning models. Scaling the features can help in handling such cases. By transforming the data to a standardized range, it reduces the impact of extreme values and makes the model more robust. This is particularly beneficial for algorithms that assume a normal distribution and are sensitive to outliers, such as linear regression.

### 3) Faster Convergence During Training:

For gradient descent-based algorithms, feature scaling can speed up the convergence by helping the optimization algorithm reach the minima faster. Since gradient descent updates the model parameters in steps proportional to the gradient of the error with respect to the parameter, having features on the same scale allows the algorithm to take more uniform steps towards the optimum and reduces the number of iterations needed.

### 4) Balanced Feature Influence:

When features are on different scales, there is a risk that larger-scale features will dominate the model’s decisions, while smaller-scale features are neglected. Feature scaling ensures that each feature has the opportunity to influence the model without being overshadowed by other features simply because of their scale.

### 5) Improved Algorithm Behavior:

Certain machine learning algorithms, particularly those that use distance metrics like Euclidean or Manhattan distance, assume that all features are centered around zero and have variance in the same order. Without feature scaling, the distance calculations could be skewed, leading to biases in the model and potentially misleading results. Feature scaling normalizes the range of features so that each one contributes equally to the distance calculations.

## Different Types of Feature Scaling Techniques

There are different types of feature scaling techniques as well that you will learn during machine learning free course. These are:

### 1) Normalization or Min-max scaling:

Normalization, also known as min-max scaling, transforms the features to a range between 0 and 1. It subtracts the minimum value of the feature and divides it by the range (maximum value minus minimum value). This technique is suitable when the distribution of the data does not follow a Gaussian distribution.

In [1]:
# Data Preprocessing

## Imporing packages
import numpy as np
from sklearn import preprocessing

## Making data
input_data = np.array([[2.1, -1.9, 5.5],
                      [-1.5, 2.4, 3.5],
                     [0.5, -7.9, 5.6],
                     [5.9, 2.3, -5.8]])
print("\n Original data: \n",input_data)

## Normalization or Min-max scaling
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaler_minmax = data_scaler_minmax.fit_transform(input_data)
print("\n Min max scaled data: \n",data_scaler_minmax)


 Original data: 
 [[ 2.1 -1.9  5.5]
 [-1.5  2.4  3.5]
 [ 0.5 -7.9  5.6]
 [ 5.9  2.3 -5.8]]

 Min max scaled data: 
 [[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]


### 2) Standardization:

Standardization transforms the features to have a mean of 0 and a standard deviation of 1. It subtracts the mean of the feature and divides it by the standard deviation. This technique is preferable when the data is normally distributed or when we don’t know the distribution in advance. Standardization maintains the shape of the distribution and does not bound the features to a specific range.

In [4]:
# Data Preprocessing

## Imporing packages
import numpy as np
from sklearn import preprocessing

## Making data
input_data = np.array([[2.1, -1.9, 5.5],
                      [-1.5, 2.4, 3.5],
                     [0.5, -7.9, 5.6],
                     [5.9, 2.3, -5.8]])
print("\n Original data: \n",input_data)

## Standardization
print("Mean: ", input_data.mean(axis=0))
print("Standard (Std) Deviation: ", input_data.std(axis=0))
data_scaled = preprocessing.scale(input_data)
print("\n Standardized data: \n",data_scaled)
print("Mean: ", data_scaled.mean(axis=0))
print("Standard (Std) Deviation: ", data_scaled.std(axis=0))


 Original data: 
 [[ 2.1 -1.9  5.5]
 [-1.5  2.4  3.5]
 [ 0.5 -7.9  5.6]
 [ 5.9  2.3 -5.8]]
Mean:  [ 1.75  -1.275  2.2  ]
Standard (Std) Deviation:  [2.71431391 4.20022321 4.69414529]

 Standardized data: 
 [[ 0.12894603 -0.14880162  0.70300338]
 [-1.19735598  0.8749535   0.27694073]
 [-0.46052153 -1.57729713  0.72430651]
 [ 1.52893149  0.85114524 -1.70425062]]
Mean:  [1.11022302e-16 0.00000000e+00 0.00000000e+00]
Standard (Std) Deviation:  [1. 1. 1.]


### 3) Normalizing

Normalization is the process of scaling individual samples to have unit norm. This process can be useful if you plan to use a quadratic form such as the dot-product or any other kernel to quantify the similarity of any pair of samples. This assumption is the base of the Vector Space Model often used in text classification and clustering contexts. The function normalize provides a quick and easy way to perform this operation on a single array-like dataset, either using the l1, l2, or max norms:

In [5]:
# Data Preprocessing

## Imporing packages
import numpy as np
from sklearn import preprocessing

## Making data
input_data = np.array([[2.1, -1.9, 5.5],
                      [-1.5, 2.4, 3.5],
                     [0.5, -7.9, 5.6],
                     [5.9, 2.3, -5.8]])
print("\n Original data: \n",input_data)

## Normalizing
data_normalized_l1 = preprocessing.normalize(input_data, norm="l1")
print("\n l1 normalized data: \n",data_normalized_l1)
# least square
data_normalized_l2 = preprocessing.normalize(input_data, norm="l2")
print("\n l2 normalized data: \n",data_normalized_l2)


 Original data: 
 [[ 2.1 -1.9  5.5]
 [-1.5  2.4  3.5]
 [ 0.5 -7.9  5.6]
 [ 5.9  2.3 -5.8]]

 l1 normalized data: 
 [[ 0.22105263 -0.2         0.57894737]
 [-0.2027027   0.32432432  0.47297297]
 [ 0.03571429 -0.56428571  0.4       ]
 [ 0.42142857  0.16428571 -0.41428571]]

 l2 normalized data: 
 [[ 0.33946114 -0.30713151  0.88906489]
 [-0.33325106  0.53320169  0.7775858 ]
 [ 0.05156558 -0.81473612  0.57753446]
 [ 0.68706914  0.26784051 -0.6754239 ]]


## Practical Examples and Best Practices for Feature Scaling

Understanding feature scaling in theory is one thing, but applying it correctly in practice is equally important. Consider the following best practices:

### 1) Feature Scaling Workflow:

When applying feature scaling, it’s crucial to fit the scaler on the training data and then use the same scaler to transform the test data. This ensures consistency and prevents data leakage. Furthermore, it’s beneficial to evaluate the impact of feature scaling on your specific machine learning task to determine which method works best.

### 2) Handling Categorical Variables:

Feature scaling is not typically applied to categorical variables, as their values represent different categories and do not have a numerical scale. Categorical variables may require additional preprocessing techniques such as one-hot encoding before being used in machine learning algorithms.

### 3) Dealing with Time-Series Data:

For time-series data, feature scaling can be applied to each individual time series or across all time series, depending on the context. Consider the characteristics of your data and the requirements of your machine learning model to make an informed decision.

## Conclusion

Feature scaling plays a crucial role in machine learning by ensuring that all features are on a similar scale, preventing bias towards certain features. It improves the performance and convergence of many machine learning algorithms. As the field of machine learning continues to evolve, new feature scaling methods and techniques may emerge. It’s important to stay updated and choose the most appropriate feature scaling method for each specific task. Remember, a well-scaled feature is a step closer to a well-performing model.